### ISSUE TITLE
Persistence isn't working on mobile browsers

### ISSUE THREAD

**Issue by alexandrepaiva-dev** [use-cookie-consent/use-cookie-consent-react#8]
Hi,

I'm having some issues with this library on mobile phones. When I close the mobile browser app (not minimize but really close the app) and open again, the selections are gone. It's not persistancing when closing/opening the app again.

I've tested on Chrome (Android/Iphone) an Safari (Iphone) and this is happening. On desktop is fine.

URL test:

https://test-koeaboa-b6su1gf97-alexandrepaiva-dev.vercel.app/

How to fix it?

Thank you

Edit1:

Version used: "@use-cookie-consent/react": "^0.3.6"

**Comment by lokty** [comment]
@alexandrepaiva-dev Did you find a fix for this? I'm still facing this issue.

**Comment by gian-reto** [comment]
@alexandrepaiva-dev @lokty I had a similar issue, but with Safari on desktop. I guess Safari ends the session when it's fully closed, so the cookie will expire. Might be the same problem you have. As it looks like in the code, `@use-cookie-consent/react` uses the [`js-cookie`](https://github.com/js-cookie/js-cookie) package under the hood, and it's possible to pass options to it when you create the `CookieConsentProvider` using the `useCookieConsentHooksOptions` prop. 

Therefore it's possible to set an expiration (in number of days), instead of the default duration value (`session`):

```ts
<CookieConsentProvider
  useCookieConsentHooksOptions={{
    consentCookieAttributes: { expires: 120 }, // ~ 4 months
  }}
>
  // ... children
</CookieConsentProvider>
```

Hope that fixes your issue as well ✌️
